Add reset Password Functionality in boiler plate
CoalAI/boilerplate-django pull request #6
Opened 2023-01-31 08:57 UTC by aishatasaduq

#4

2023-01-31 11:37 UTC, aishatasaduq commented
@ammarhaider001 I need to update readme as well. do not merge it yet.

2023-01-31 16:29 UTC, ammarhaider001 requested changes

2023-01-31 16:29 UTC, ammarhaider001 commented on interface/models.py
> +def password_reset_token_created(sender, instance, reset_password_token, *args, **kwargs):
why is this logic inside models file  ?

2023-01-31 16:46 UTC, aishatasaduq commented on interface/models.py
> +def password_reset_token_created(sender, instance, reset_password_token, *args, **kwargs):
should i put it in signals.py file?

2023-01-31 16:46 UTC, aishatasaduq commented on interface/models.py
> +def password_reset_token_created(sender, instance, reset_password_token, *args, **kwargs):
should i put it in signals.py file?

2023-02-01 07:06 UTC, aishatasaduq commented on interface/models.py
> +def password_reset_token_created(sender, instance, reset_password_token, *args, **kwargs):
@ammarhaider001 changes done

2023-02-03 20:51 UTC, ammarhaider001 requested changes

2023-02-06 07:17 UTC, aishatasaduq commented on interface/apps.py
> +        import interface.signals
The reason the signals are imported here is because Django will not import the signals if you do not import those explicitly.

2023-02-06 07:17 UTC, aishatasaduq commented on project/urls.py
> +    path("api/password_reset/", include('django_rest_passwordreset.urls', namespace='password_reset'))
done

2023-02-06 09:44 UTC, aishatasaduq commented
Kindly do not merge this PR yet

2023-02-06 13:09 UTC, merged